# Forum languages
# These settings are needed because forum languages and /learn/(language here) are different
# /learn/(language here) - These are under curriculum_slug below
languages:
  default: espanol|chinese|chinese-traditional|italiano|portugues|ukrainian|japanese
  description: "Languages forum slug names which are also available on freeCodeCamp curriculum"
  type: list
  list_type: simple
  choices:
    - espanol
    - chinese
    - chinese-traditional # This does not exist on forum currently, but is used to correspond to curriculum_slug id
    - italiano
    - portugues
    - ukrainian
    - japanese

# Navigation
curriculum_title:
  default: Visit the Curriculum
  description: "Text displayed in the curriculum navigation item"
curriculum_title_short:
  default: Curriculum
  description: "The short version of curriculum title used for mobile devices"
curriculum_src:
  default: https://www.freecodecamp.org/learn/
  description: "The link to related language curriculum"
curriculum_slug:
  default: espanol|chinese|chinese-traditional|italian|portuguese|ukrainiai|japanese
  description: "Slug attached to curriculum_src"
  type: list
  list-type: simple
  choices:
    - espanol
    - chinese
    - chinese-traditional # This does not exist on forum currently, but is used to correspond to curriculum_slug id
    - italian
    - portuguese
    - ukrainian
    - japanese

# Analytics
Google_Tag_Manager:
  default: ""
  description: "Google Tag Manager ID"

# Footer description section
footer_paragraph_1:
  default: "freeCodeCamp is a donor-supported tax-exempt 501(c)(3) nonprofit
    organization (United States Federal Tax Identification Number:
    82-0779546)"
  description: "First footer paragraph"
footer_paragraph_2:
  default:
    "Our mission: to help people learn to code for free. We accomplish this
    by creating thousands of videos, articles, and interactive coding
    lessons - all freely available to the public."
  description: "Second footer paragraph"
footer_paragraph_3:
  default: "Donations to freeCodeCamp go toward our education initiatives, and
    help pay for servers, services, and staff."
  description: "Second footer paragraph"
footer_donation_cta:
  default: "You can make a tax-deductible donation here."
  description: "Footer donation paragraph"

# Footer columns section
footer_columns_header:
  default: "Trending Guides"
  description: "Header for footer link columns"
article0title: "Binary Search in C++"
article0link: "https://www.freecodecamp.org/news/binary-search-in-c-algorithm-example/"
article1title: "Binary Search in Java"
article1link: "https://www.freecodecamp.org/news/binary-search-in-java-algorithm-example/"
article2title: "Lambda Sort in Python"
article2link: "https://www.freecodecamp.org/news/lambda-sort-list-in-python/"
article3title: "List Flatten in Python"
article3link: "https://www.freecodecamp.org/news/list-flatten-in-python-flattening-nested-lists/"
article4title: "Python Print Exception"
article4link: "https://www.freecodecamp.org/news/python-print-exception-how-to-try-except-print-an-error/"
article5title: "Enhanced Java for-loops"
article5link: "https://www.freecodecamp.org/news/enhanced-for-loops-in-java-how-to-use-foreach-loops-on-arrays/"
article6title: "JS Comparison Operators"
article6link: "https://www.freecodecamp.org/news/javascript-comparison-operators-how-to-compare-objects-for-equality-in-js/"
article7title: "Python Program Examples"
article7link: "https://www.freecodecamp.org/news/python-program-examples-simple-code-examples-for-beginners/"
article8title: "Create a Dict in Python"
article8link: "https://www.freecodecamp.org/news/create-a-dictionary-in-python-python-dict-methods/"
article9title: "Python Remove from List"
article9link: "https://www.freecodecamp.org/news/python-remove-from-list-how-to-remove-an-item-from-a-list-in-python-2/"
article10title: "Pip Upgrade"
article10link: "https://www.freecodecamp.org/news/pip-upgrade-and-how-to-update-pip-and-python/"
article11title: "Undo Git Add"
article11link: "https://www.freecodecamp.org/news/undo-git-add-how-to-remove-added-files-in-git/"
article12title: "Operators in C"
article12link: "https://www.freecodecamp.org/news/c-operator-logic-operators-in-c-programming/"
article13title: "Dataframe to CSV"
article13link: "https://www.freecodecamp.org/news/dataframe-to-csv-how-to-save-pandas-dataframes-by-exporting/"
article14title: "JavaScript Replace"
article14link: "https://www.freecodecamp.org/news/javascript-replace-how-to-replace-a-string-or-substring-in-js/"
article15title: "What is R Squared?"
article15link: "https://www.freecodecamp.org/news/what-is-r-squared-r2-value-meaning-and-definition/"
article16title: "Git Squash Commits"
article16link: "https://www.freecodecamp.org/news/git-squash-commits/"
article17title: "Integer Array in C"
article17link: "https://www.freecodecamp.org/news/how-to-declare-integer-arrays-with-c-programming/"
article18title: "Gradient Descent ML"
article18link: "https://www.freecodecamp.org/news/gradient-descent-machine-learning-algorithm-example/"
article19title: "JS Ternary Operator"
article19link: "https://www.freecodecamp.org/news/how-to-use-the-ternary-operator-in-javascript/"
article20title: "Print Newline in Python"
article20link: "https://www.freecodecamp.org/news/print-newline-in-python/"
article21title: "Bash Scripting Tutorial"
article21link: "https://www.freecodecamp.org/news/bash-scripting-tutorial-linux-shell-script-and-command-line-for-beginners/"
article22title: "Create an Array in Java"
article22link: "https://www.freecodecamp.org/news/how-to-create-an-array-in-java/"
article23title: "Trim a String in Python"
article23link: "https://www.freecodecamp.org/news/how-to-strip-trailing-whitespace-in-python/"
article24title: "Static Variables in Java"
article24link: "https://www.freecodecamp.org/news/static-variables-in-java/"
article25title: "What Does => Mean in JS?"
article25link: "https://www.freecodecamp.org/news/what-does-the-hashrocket-symbol-mean-in-javascript/"
article26title: "Python Iterate Over Dict"
article26link: "https://www.freecodecamp.org/news/python-iterate-over-dictionary-how-to-loop-through-a-dict/"
article27title: "Install Node.js on Ubuntu"
article27link: "https://www.freecodecamp.org/news/how-to-install-node-js-on-ubuntu/"
article28title: "SQL Where Contains String"
article28link: "https://www.freecodecamp.org/news/sql-where-contains-string-substring-query-example/"
article29title: "How to Join Lists in Python"
article29link: "https://www.freecodecamp.org/news/joining-lists-in-python-how-to-concat-lists/"

footer_our_org_header:
  default: "Our Nonprofit"
  description: "Title for organizational links"
footer_about_link: "https://www.freecodecamp.org/news/about/"
footer_about_text: "About"
footer_Alumni_Network_link: "https://www.linkedin.com/school/free-code-camp/people/"
footer_Alumni_Network_text: "Alumni Network"
footer_Open_Source_link: "https://github.com/freeCodeCamp/"
footer_Open_Source_text: "Open Source"
footer_Shop_link: "https://www.freecodecamp.org/shop/"
footer_Shop_text: "Shop"
footer_Support_link: "https://www.freecodecamp.org/news/support/"
footer_Support_text: "Support"
footer_Sponsors_link: "https://www.freecodecamp.org/news/sponsors/"
footer_Sponsors_text: "Sponsors"
footer_Academic_Honesty_link: "https://www.freecodecamp.org/news/academic-honesty-policy/"
footer_Academic_Honesty_text: "Academic Honesty"
footer_Code_of_Conduct_link: "https://www.freecodecamp.org/news/code-of-conduct/"
footer_Code_of_Conduct_text: "Code of Conduct"
footer_Privacy_Policy_link: "https://www.freecodecamp.org/news/privacy-policy/"
footer_Privacy_Policy_text: "Privacy Policy"
footer_Terms_of_Service_link: "https://www.freecodecamp.org/news/terms-of-service/"
footer_Terms_of_Service_text: "Terms of Service"
footer_Copyright_Policy_link: "https://www.freecodecamp.org/news/copyright-policy/"
footer_Copyright_Policy_text: "Copyright Policy"
