# Navigation
curriculum_title:
  default: Visit the Curriculum
  description: "This text will be displayed in the curriculum navigation item"
curriculum_title_short:
  default: Curriculum
  description: "This is the short version of curriculum title used for mobile devices"
curriculum_src:
  default: https://www.freecodecamp.org/learn
  description: "This the link to related language curriculum"

# Analytics
Google_Tag_Manager:
  default: ""
  description: "Google Tag Manager ID"

# Footer description section
footer_paragraph_1:
  default: "freeCodeCamp is a donor-supported tax-exempt 501(c)(3) nonprofit
    organization (United States Federal Tax Identification Number:
    82-0779546)"
  description: "First footer paragraph"
footer_paragraph_2:
  default:
    "Our mission: to help people learn to code for free. We accomplish this
    by creating thousands of videos, articles, and interactive coding
    lessons - all freely available to the public. We also have thousands
    of freeCodeCamp study groups around the world."
  description: "Second footer paragraph"
footer_paragraph_3:
  default: "Donations to freeCodeCamp go toward our education initiatives, and
    help pay for servers, services, and staff."
  description: "Second footer paragraph"
footer_donation_cta:
  default: "You can make a tax-deductible donation here."
  description: "Footer donation paragraph"

# Footer columns section
footer_columns_header:
  default: "Trending Guides"
  description: "Header for footer link columns"
article0title: "Bash If Statement"
article0link: "https://www.freecodecamp.org/news/bash-if-statement-linux-shell-if-else-syntax-example/"
article1title: "Align Text in HTML"
article1link: "https://www.freecodecamp.org/news/how-to-align-text-in-html/"
article2title: "JS Copy an Object"
article2link: "https://www.freecodecamp.org/news/clone-an-object-in-javascript/"
article3title: "Tableau vs Power BI"
article3link: "https://www.freecodecamp.org/news/tableau-vs-power-bi-whats-the-difference/"
article4title: "What is rem in CSS?"
article4link: "https://www.freecodecamp.org/news/what-is-rem-in-css-rem-unit-font-size-padding-height-and-more/"
article5title: "Quick Sort Algorithm"
article5link: "https://www.freecodecamp.org/news/quick-sort-algorithm-time-complexity-with-cpp-and-java-code/"
article6title: "How to Open XML Files"
article6link: "https://www.freecodecamp.org/news/how-to-open-an-xml-file/"
article7title: "Whatâ€™s Node Used For?"
article7link: "https://www.freecodecamp.org/news/node-js-server-side-javascript-what-is-node-used-for/"
article8title: "Declare an Array in JS"
article8link: "https://www.freecodecamp.org/news/how-to-declare-an-array-in-javascript-creating-an-array-in-js/"
article9title: "Python String Contains"
article9link: "https://www.freecodecamp.org/news/python-string-contains-python-3-substring-tutorial-2/"
article10title: "CS vs IT"
article10link: "https://www.freecodecamp.org/news/computer-science-vs-information-technology-whats-the-difference/"
article11title: "JS Append"
article11link: "https://www.freecodecamp.org/news/javascript-add-to-an-array-js-append/"
article12title: "SQL Select"
article12link: "https://www.freecodecamp.org/news/sql-select-statement-and-query-examples/"
article13title: "PHP Explode"
article13link: "https://www.freecodecamp.org/news/php-explode-how-to-split-a-string-into-an-array/"
article14title: "PHP Implode"
article14link: "https://www.freecodecamp.org/news/php-implode-convert-array-to-string-with-join/"
article15title: "What is YAML?"
article15link: "https://www.freecodecamp.org/news/what-is-yaml-the-yml-file-format/"
article16title: "What is an ORM?"
article16link: "https://www.freecodecamp.org/news/what-is-an-orm-the-meaning-of-object-relational-mapping-database-tools/"
article17title: "SOLID Principles"
article17link: "https://www.freecodecamp.org/news/solid-principles-for-programming-and-software-design/"
article18title: "SQL Date Example"
article18link: "https://www.freecodecamp.org/news/sql-date-function-query-timestamp-example-format/"
article19title: "JavaScript Minify"
article19link: "https://www.freecodecamp.org/news/javascript-minify-minifying-js-with-a-minifier-or-jsmin/"
article20title: "Append String in Python"
article20link: "https://www.freecodecamp.org/news/append-a-string-in-python-str-appending/"
article21title: "What is Data Analytics?"
article21link: "https://www.freecodecamp.org/news/what-is-data-analytics-data-analysis-and-definition-for-beginners/"
article22title: "Git Revert to Last Commit"
article22link: "https://www.freecodecamp.org/news/git-reverting-to-previous-commit-how-to-revert-to-last-commit/"
article23title: "What is an IDE in Coding?"
article23link: "https://www.freecodecamp.org/news/what-is-an-ide-for-beginners/"
article24title: "Convert Int to String C++"
article24link: "https://www.freecodecamp.org/news/how-to-convert-an-int-to-a-string-in-cpp/"
article25title: "Data Analyst vs Scientist"
article25link: "https://www.freecodecamp.org/news/data-analyst-vs-data-scientist-whats-the-difference/"
article26title: "Lowercase a Python String"
article26link: "https://www.freecodecamp.org/news/how-to-lowercase-python-string/"
article27title: "Stratified Random Sampling"
article27link: "https://www.freecodecamp.org/news/what-is-stratified-random-sampling-definition-and-python-example/"
article28title: "Linux Environment Variables"
article28link: "https://www.freecodecamp.org/news/how-to-set-an-environment-variable-in-linux/"
article29title: "Which Programming Language?"
article29link: "https://www.freecodecamp.org/news/the-best-programming-language-to-learn-beginners-guide-to-coding/"

footer_our_org_header:
  default: "Our Nonprofit"
  description: "Title for organizational links"
footer_about_link: "https://www.freecodecamp.org/news/about/"
footer_about_text: "About"
footer_Alumni_Network_link: "https://www.linkedin.com/school/free-code-camp/people/"
footer_Alumni_Network_text: "Alumni Network"
footer_Open_Source_link: "https://github.com/freeCodeCamp/"
footer_Open_Source_text: "Open Source"
footer_Shop_link: "https://www.freecodecamp.org/shop/"
footer_Shop_text: "Shop"
footer_Support_link: "https://www.freecodecamp.org/news/support/"
footer_Support_text: "Support"
footer_Sponsors_link: "https://www.freecodecamp.org/news/sponsors/"
footer_Sponsors_text: "Sponsors"
footer_Academic_Honesty_link: "https://www.freecodecamp.org/news/academic-honesty-policy/"
footer_Academic_Honesty_text: "Academic Honesty"
footer_Code_of_Conduct_link: "https://www.freecodecamp.org/news/code-of-conduct/"
footer_Code_of_Conduct_text: "Code of Conduct"
footer_Privacy_Policy_link: "https://www.freecodecamp.org/news/privacy-policy/"
footer_Privacy_Policy_text: "Privacy Policy"
footer_Terms_of_Service_link: "https://www.freecodecamp.org/news/terms-of-service/"
footer_Terms_of_Service_text: "Terms of Service"
footer_Copyright_Policy_link: "https://www.freecodecamp.org/news/copyright-policy/"
footer_Copyright_Policy_text: "Copyright Policy"
